import type { VercelRequest, VercelResponse } from '@vercel/node';
import { getAccessToken, SHORTCODE, BASE_URL, generateTimestamp, generatePassword, getCorsOrigin } from './_mpesa-auth';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const origin = getCorsOrigin(req);
  res.setHeader('Access-Control-Allow-Origin', origin);
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { checkoutRequestId } = req.body as { checkoutRequestId: string };
  if (!checkoutRequestId) return res.status(400).json({ error: 'checkoutRequestId required' });

  // Auto-approve test checkout IDs generated by the sandbox test number flow
  if (checkoutRequestId.startsWith('ws_CO_TEST_')) {
    return res.status(200).json({
      paid: true,
      cancelled: false,
      resultCode: '0',
      resultDesc: 'The service request is processed successfully.',
    });
  }

  try {
    const token = await getAccessToken();
    const timestamp = generateTimestamp();
    const password = generatePassword(timestamp);

    const queryRes = await fetch(`${BASE_URL}/mpesa/stkpushquery/v1/query`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        BusinessShortCode: SHORTCODE,
        Password: password,
        Timestamp: timestamp,
        CheckoutRequestID: checkoutRequestId,
      }),
    });

    const data = await queryRes.json() as {
      ResultCode?: string;
      ResultDesc?: string;
      ResponseCode?: string;
      ResponseDescription?: string;
    };

    const paid = data.ResultCode === '0';
    const cancelled = data.ResultCode === '1032';

    return res.status(200).json({
      paid,
      cancelled,
      resultCode: data.ResultCode,
      resultDesc: data.ResultDesc || data.ResponseDescription,
    });
  } catch (err) {
    console.error('Query error:', err);
    return res.status(500).json({ error: 'Failed to query payment status' });
  }
}
